<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="v2cloud-pc" ignored="0" name="CheckLoginHistoryPage" tests="5" failures="2" timestamp="17 Apr 2017 06:11:13 GMT" time="13.573" errors="0">
  <testcase name="A_Login_IncorrectPassword" time="3.797" classname="testCases.Validate_LoginHistoryPage"/>
  <testcase name="Login" time="1.784" classname="testCases.Validate_LoginHistoryPage"/>
  <testcase name="NavigateToLoginHistoryPage" time="2.624" classname="testCases.Validate_LoginHistoryPage">
    <failure type="java.lang.AssertionError" message="expected [Historique de connexion] but found [Login History]">
      <![CDATA[java.lang.AssertionError: expected [Historique de connexion] but found [Login History]
	at appModules.LoginHistory_Action.Execute(LoginHistory_Action.java:12)
	at appModules.Navigation_Action.Navigate_To_LoginHistoryPage(Navigation_Action.java:63)
	at testCases.Validate_LoginHistoryPage.NavigateToLoginHistoryPage(Validate_LoginHistoryPage.java:35)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- NavigateToLoginHistoryPage -->
  <testcase name="Check_NewEntries" time="0.36" classname="testCases.Validate_LoginHistoryPage">
    <failure type="java.lang.AssertionError" message="expected [Réussite] but found [Successful]">
      <![CDATA[java.lang.AssertionError: expected [Réussite] but found [Successful]
	at appModules.LoginHistory_Action.ExecuteCheckLatest(LoginHistory_Action.java:18)
	at testCases.Validate_LoginHistoryPage.Check_NewEntries(Validate_LoginHistoryPage.java:42)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Check_NewEntries -->
  <testcase name="CheckTotalRows" time="0.077" classname="testCases.Validate_LoginHistoryPage"/>
</testsuite> <!-- CheckLoginHistoryPage -->
